const services = [
  {
    title: "Frontend Developer",
    icon: "/web.png",
  },
  {
    title: "Backend Developer",
    icon: "/mobile.png",
  },
  {
    title: "Fullstack Developer",
    icon: "/backend.png",
  },
  {
    title: "Mobile Developer",
    icon: "/creator.png",
  },
];
const experiences = [
  {
    title: "React js ",
    company_name: "JavaScript library",
    icon: "/react.png",
    iconBg: "#383E56",
    date: "---- March 2020 - April 2021",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Node js",
    company_name: "Backend JavaScript runtime",
    icon: "/node-js.png",
    iconBg: "#E6DEDD",
    date: "Jan 2021 - Feb 2022 ----",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Full stack Developer",
    company_name: "Full stack framework ",
    icon: "/next.png",
    iconBg: "#383E56",
    date: "---- Jan 2022 - Jan 2023",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "React Native & Flutter",
    company_name: "Mobile development framework",
    icon: "/flutter.png",
    iconBg: "#E6DEDD",
    date: "Jan 2023 - Present ----",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "React Native & Flutter",
    company_name: "Mobile development framework",
    icon: "/flutter.png",
    iconBg: "#E6DEDD",
    date: "Jan 2023 - Present ----",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "React Native & Flutter",
    company_name: "Mobile development framework",
    icon: "/flutter.png",
    iconBg: "#E6DEDD",
    date: "Jan 2023 - Present ----",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
];

const Projectdata = [
  {
    colour: "bg-[#EEEEEE]",
    title: "Deliveroo Mobile App ( ReactNative + Type Script + Tailwinds css )",
    company_name: "Frontend + Backend (React Native App)",
    icon: "/favicon.png",
    isMobile: true,
    iconBg: "#E6DEDD",
    PROJECT_SHORT_NAME: "DeliverooMobileApp",
    PROJECT_NAME:
      "Deliveroo Mobile App ( ReactNative + Type Script + Tailwinds css )",
    PROJECT_IMG: "/deliveroo1.jpg",
    PROJECT_IMG2: "/deliveroo2.jpg",
    PROJECT_IMG3: "/deliveroo3.jpg",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "",
    react: "/react.png",
    redux: "/redux.png",
    icons: "",
    pusher: "/postger.png",
    nodejs: "/nodejs.png",
    Express: "Express",
    mongodb: "",
    Firebase: "",
    mysql: "",
    postger: "/prisma.webp",
    prisma: "",
    Nextjs: "",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/Deliveroo_Mobile.apk.git",
    Backend_Repo_Link: "https://github.com/HyatMyat4/Deliveroo.git",
    PROJECT_VIDEO: "AxQ_Eli8gtk",
    LIVE_MODE: "",
    PROJECT_TEXT:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo   ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "https://cdn.worldvectorlogo.com/logos/react-1.svg",
      "/redux.png",
      "https://d4.alternativeto.net/R_1V_-fGcOKhBvZ8WmsemEDDh9doSDY_AJSDB3qzNQk/rs:fill:280:280:0/g:ce:0:0/YWJzOi8vZGlzdC9pY29ucy9oZXJvaWNvbnNfMjEyNTIwLnBuZw.png",
      "/nodejs.png",
      "Express",
      "/postger.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React Native",
      "Redux",
      "TailwindCss",
      "Heros-icons",
      "Type Script",
    ],
    langauge_Backend: ["Node js", "Express Js", "Google Auth", "Postger Sql"],
  },
  {
    colour: "bg-[#EEEEEE]",
    title: "Shoe Ecommerce & AdminDashboard",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/favicon.png",
    isMobile: false,
    iconBg: "#E6DEDD",
    PROJECT_SHORT_NAME: "FullStackShoeEcommerce&AdminDashboard",
    PROJECT_NAME: "Shoe Ecommerce & AdminDashboard (Responsive Web App)",
    PROJECT_IMG: "/nikedashboard.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "/postger.png",
    nodejs: "/nodejs.png",
    Express: "Express",
    mongodb: "",
    Firebase: "/Firebase.png",
    mysql: "/stripe.webp",
    postger: "/webhook.svg",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/nike_store.git",
    Backend_Repo_Link: "https://github.com/HyatMyat4/Nike_Backend.git",
    PROJECT_VIDEO: "v3LJMcWbcDQ",
    LIVE_MODE: "",
    PROJECT_TEXT:
      "A Real Time Full Stack Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD  Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth  ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "",
      "/react.png",
      "/redux.png",
      "/icons.svg",
      "/nodejs.png",
      "Express",
      "/Firebase.png",
      "/stripe.webp",
      "/webhook.svg",
      "/next.png",
      "/postger.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "TailwindCss",
      "Material-ui",
      "React-icons",
      "Type Script",
      "Next JS",
    ],
    langauge_Backend: [
      "Node js",
      "Express Js",
      "Jwt Auth",
      "FireBase Db",
      "Postger Sql",
      "Next Auth",
      "Stripe",
    ],
  },
  {
    colour: "bg-[#EEEEEE]",
    title: "Shoe Ecommerce & AdminDashboard",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/favicon.png",
    iconBg: "#E6DEDD",
    isMobile: false,
    PROJECT_SHORT_NAME: "FullStackShoeEcommerce&AdminDashboard",
    PROJECT_NAME: "Shoe Ecommerce & AdminDashboard (Responsive Web App)",
    PROJECT_IMG: "/nikefrontend.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "/postger.png",
    nodejs: "/nodejs.png",
    Express: "Express",
    mongodb: "",
    Firebase: "/Firebase.png",
    mysql: "/stripe.webp",
    postger: "/webhook.svg",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/nike_store.git",
    Backend_Repo_Link: "https://github.com/HyatMyat4/Nike_Backend.git",
    PROJECT_VIDEO: "v3LJMcWbcDQ",
    LIVE_MODE: "",
    PROJECT_TEXT:
      "A Real Time Full Stack Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD  Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth  ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "",
      "/react.png",
      "/redux.png",
      "/icons.svg",
      "/nodejs.png",
      "Express",
      "/Firebase.png",
      "/stripe.webp",
      "/webhook.svg",
      "/next.png",
      "/postger.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "TailwindCss",
      "Material-ui",
      "React-icons",
      "Type Script",
      "Next JS",
    ],
    langauge_Backend: [
      "Node js",
      "Express Js",
      "Jwt Auth",
      "FireBase Db",
      "Postger Sql",
      "Next Auth",
      "Stripe",
    ],
  },
  {
    colour: "bg-[#23242A]",
    title: "FullStackSocalMedia",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/grape.png",
    iconBg: "#383E56",
    isMobile: false,
    PROJECT_SHORT_NAME: "FullStackSocalMedia",
    PROJECT_NAME: "Full Stack SocalMedia (Responsive Web App)",
    PROJECT_IMG: "/project2.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "/mui.png",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "/pusher.png",
    nodejs: "/nodejs.png",
    Express: "Express",
    mongodb: "/mongodb.png",
    Firebase: "",
    mysql: "",
    postger: "",
    prisma: "",
    Nextjs: "",
    Ts: "",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/GrapeMedia.git",
    Backend_Repo_Link: "https://github.com/HyatMyat4/SocialMediaBackend-.git",
    PROJECT_VIDEO: "cLKsNVSyPMM",
    LIVE_MODE: "",
    PROJECT_TEXT:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text",
    USER_LANGUAGE_IMG: [
      "/js.png",
      "/tailwind.png",
      "/mui.png",
      "/react.png",
      "/redux.png",
      "/icons.svg",
      "/pusher.png",
      "/nodejs.png",
      "Express",
      "/mongodb.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "TailwindCss",
      "Material-ui",
      "React-icons",
    ],
    langauge_Backend: ["Node js", "Express Js", "Jwt Auth", "Mongo Db"],
  },
  {
    colour: "bg-[#EEEEEE]",
    title: "FoodOrder & AdminDashboard",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/food.png",
    iconBg: "#E6DEDD",
    isMobile: false,
    PROJECT_SHORT_NAME: "FullStackFoodOrder&AdminDashboard",
    PROJECT_NAME: "FullStackFood Order & AdminDashboard (Responsive Web App)",
    PROJECT_IMG: "/FoodDashboard.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "/mui.png",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "/graphql.png",
    nodejs: "/nodejs.png",
    Express: "Express",
    mongodb: "",
    Firebase: "/Firebase.png",
    mysql: "/stripe.webp",
    postger: "/webhook.svg",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/AdminDashboard.git",
    Backend_Repo_Link: "https://github.com/HyatMyat4/DeshboardBackend.git",
    PROJECT_VIDEO: "yF1oJ7wzvWY",
    LIVE_MODE: "https://admin-dashboard-hyatmyat4.vercel.app/",
    PROJECT_TEXT:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin only can delete User and Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Git hub , instgram , Face Book , FastFood Auth     ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "/mui.png",
      "/react.png",
      "/redux.png",
      "/icons.svg",
      "/nodejs.png",
      "Express",
      "/Firebase.png",
      "/stripe.webp",
      "/webhook.svg",
      "/next.png",
      "/graphql.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "TailwindCss",
      "Material-ui",
      "React-icons",
      "Type Script",
    ],
    langauge_Backend: [
      "Node js",
      "Express Js",
      "Jwt Auth",
      "FireBase Db",
      "Graphql",
      "Next JS",
      "Stripe",
    ],
  },
  {
    colour: "bg-[#EEEEEE]",
    title: "FoodOrder & AdminDashboard",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/food.png",
    iconBg: "#E6DEDD",
    isMobile: false,
    PROJECT_SHORT_NAME: "FullStackFoodOrder&AdminDashboard",
    PROJECT_NAME: "FullStackFood Order & AdminDashboard (Responsive Web App)",
    PROJECT_IMG: "/pj2.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "/mui.png",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "/graphql.png",
    nodejs: "/nodejs.png",
    Express: "Express",
    mongodb: "",
    Firebase: "/Firebase.png",
    mysql: "/stripe.webp",
    postger: "/webhook.svg",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/AdminDashboard.git",
    Backend_Repo_Link: "https://github.com/HyatMyat4/DeshboardBackend.git",
    PROJECT_VIDEO: "yF1oJ7wzvWY",
    LIVE_MODE: "https://admin-dashboard-hyatmyat4.vercel.app/",
    PROJECT_TEXT:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin only can delete User and Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Git hub , instgram , Face Book , FastFood Auth     ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "/mui.png",
      "/react.png",
      "/redux.png",
      "/icons.svg",
      "/nodejs.png",
      "Express",
      "/Firebase.png",
      "/stripe.webp",
      "/webhook.svg",
      "/next.png",
      "/graphql.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "TailwindCss",
      "Material-ui",
      "React-icons",
      "Type Script",
    ],
    langauge_Backend: [
      "Node js",
      "Express Js",
      "Jwt Auth",
      "FireBase Db",
      "Graphql",
      "Next JS",
      "Stripe",
    ],
  },
  {
    colour: "bg-[#444654]",
    title: "AI ChatGPT Fake",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/chatgpt.png",
    iconBg: "#E6DEDD",
    isMobile: false,
    PROJECT_SHORT_NAME: "AI ChatGPT Fake",
    PROJECT_NAME: "AI ChatGPT Fullstack (Responsive Web App)",
    PROJECT_IMG: "/gpt.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "/reactquery.png",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "",
    nodejs: "",
    Express: "",
    mongodb: "",
    Firebase: "/Firebase.png",
    mysql: "",
    postger: "",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/Chat_GPT4.git",
    Backend_Repo_Link: "",
    PROJECT_VIDEO: "R90bxY4UwPg",
    LIVE_MODE: "https://chat-gpt-4-five.vercel.app/chat/htMjkxbzMJfPgpbbOCT7",
    PROJECT_TEXT:
      "A Real Time You Can Ask any thing & you can create new chat delete chat & Clear conversations Feature and google , microsoft Auth   ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "/react.png",
      "/redux.png",
      "/reactquery.png",
      "/icons.svg",
      "/next.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "ReactQuery",
      "TailwindCss",
      "React-icons",
      "Type Script",
    ],
    langauge_Backend: ["Next JS"],
  },
  {
    colour: "bg-[#090909]",
    title: "ApexLegnds.com_Clone",
    company_name: "Frontend  (Responsive Web App) ",
    icon: "/apex.svg",
    iconBg: "#383E56",
    isMobile: false,
    PROJECT_SHORT_NAME: "ApexLegnds.com_Clone",
    PROJECT_NAME: "ApexLegnds.com Clone (Responsive Web App)",
    PROJECT_IMG: "/pj3.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "",
    nodejs: "",
    Express: "",
    mongodb: "",
    Firebase: "",
    mysql: "",
    postger: "",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    PROJECT_VIDEO: "IqYbA6ZZ-e4",
    LIVE_MODE: "https://apex-legends-seven.vercel.app/",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/ApexLegends.com.git",
    Backend_Repo_Link: "",
    PROJECT_TEXT:
      "Simple ApexLegnds Game Web application DropDown Feature Complex Responsive ",
    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "/react.png",
      "/redux.png",
      "/icons.svg",
      "/next.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "Type Script",
      "React",
      "Redux",
      "TailwindCss",
      "React-icons",
      "Next JS",
    ],
    langauge_Backend: [],
  },
];
const OrderBy = [
  {
    colour: "bg-[#EEEEEE]",
    title: "Deliveroo Mobile App ( ReactNative + Type Script + Tailwinds css )",
    company_name: "Frontend + Backend (React Native App)",
    icon: "/favicon.png",
    isMobile: true,
    iconBg: "#E6DEDD",
    PROJECT_SHORT_NAME: "DeliverooMobileApp",
    PROJECT_NAME:
      "Deliveroo Mobile App ( ReactNative + Type Script + Tailwinds css )",
    PROJECT_IMG:
      "https://assets-global.website-files.com/60bded7e757b99324a8f1644/60ef0f6634c2209a153a534a_Untitled_Artwork.png",
    PROJECT_IMG2: "/deliveroo2.jpg",
    PROJECT_IMG3: "/deliveroo3.jpg",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "",
    react: "/react.png",
    redux: "/redux.png",
    icons: "",
    pusher: "/postger.png",
    nodejs: "/nodejs.png",
    Express: "Express",
    mongodb: "",
    Firebase: "",
    mysql: "",
    postger: "",
    prisma: "",
    Nextjs: "",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/Deliveroo_Mobile.apk.git",
    Backend_Repo_Link: "https://github.com/HyatMyat4/Deliveroo.git",
    PROJECT_VIDEO: "AxQ_Eli8gtk",
    LIVE_MODE: "",
    PROJECT_TEXT:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo   ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "https://cdn.worldvectorlogo.com/logos/react-1.svg",
      "/redux.png",
      "https://d4.alternativeto.net/R_1V_-fGcOKhBvZ8WmsemEDDh9doSDY_AJSDB3qzNQk/rs:fill:280:280:0/g:ce:0:0/YWJzOi8vZGlzdC9pY29ucy9oZXJvaWNvbnNfMjEyNTIwLnBuZw.png",
      "/nodejs.png",
      "Express",
      "/postger.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React Native",
      "Redux",
      "TailwindCss",
      "Heros-icons",
      "Type Script",
    ],
    langauge_Backend: ["Node js", "Express Js", "Google Auth", "Postger Sql"],
  },
  {
    colour: "bg-[#E2E8F0]",
    title: "AI ChatGPT Fake",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/favicon.png",
    iconBg: "#383E56",
    PROJECT_SHORT_NAME: "AI ChatGPT Fake",
    PROJECT_NAME: "AI ChatGPT Fullstack (Responsive Web App)",
    PROJECT_IMG: "/nikedashboard.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "/reactquery.png",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "",
    nodejs: "",
    Express: "",
    mongodb: "",
    Firebase: "/Firebase.png",
    mysql: "",
    postger: "",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/Chat_GPT4.git",
    Backend_Repo_Link: "",
    PROJECT_VIDEO: "R90bxY4UwPg",
    LIVE_MODE: "https://chat-gpt-4-five.vercel.app/chat/htMjkxbzMJfPgpbbOCT7",
    PROJECT_TEXT:
      "A Real Time You Can Ask any thing & you can create new chat delete chat & Clear conversations Feature and google , microsoft Auth   ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "/react.png",
      "/redux.png",
      "/reactquery.png",
      "/icons.svg",
      "/next.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "ReactQuery",
      "TailwindCss",
      "React-icons",
      "Type Script",
    ],
    langauge_Backend: ["Next JS"],
  },
  {
    colour: "bg-[#444654]",
    title: "AI ChatGPT Fake",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/chatgpt.png",
    iconBg: "#E6DEDD",
    PROJECT_SHORT_NAME: "AI ChatGPT Fake",
    PROJECT_NAME: "AI ChatGPT Fullstack (Responsive Web App)",
    PROJECT_IMG: "/gpt.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "/reactquery.png",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "",
    nodejs: "",
    Express: "",
    mongodb: "",
    Firebase: "/Firebase.png",
    mysql: "",
    postger: "",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/Chat_GPT4.git",
    Backend_Repo_Link: "",
    PROJECT_VIDEO: "R90bxY4UwPg",
    LIVE_MODE: "https://chat-gpt-4-five.vercel.app/chat/htMjkxbzMJfPgpbbOCT7",
    PROJECT_TEXT:
      "A Real Time You Can Ask any thing & you can create new chat delete chat & Clear conversations Feature and google , microsoft Auth   ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "/react.png",
      "/redux.png",
      "/reactquery.png",
      "/icons.svg",
      "/next.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "ReactQuery",
      "TailwindCss",
      "React-icons",
      "Type Script",
    ],
    langauge_Backend: ["Next JS"],
  },
  {
    colour: "bg-[#090909]",
    title: "ApexLegnds.com_Clone",
    company_name: "Frontend  (Responsive Web App) ",
    icon: "/apex.svg",
    iconBg: "#383E56",
    PROJECT_SHORT_NAME: "ApexLegnds.com_Clone",
    PROJECT_NAME: "ApexLegnds.com Clone (Responsive Web App)",
    PROJECT_IMG: "/pj3.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "",
    nodejs: "",
    Express: "",
    mongodb: "",
    Firebase: "",
    mysql: "",
    postger: "",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    PROJECT_VIDEO: "IqYbA6ZZ-e4",
    LIVE_MODE: "https://apex-legends-seven.vercel.app/",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/ApexLegends.com.git",
    Backend_Repo_Link: "",
    PROJECT_TEXT:
      "Simple ApexLegnds Game Web application DropDown Feature Complex Responsive ",
    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "/react.png",
      "/redux.png",
      "/icons.svg",
      "/next.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "Type Script",
      "React",
      "Redux",
      "TailwindCss",
      "React-icons",
      "Next JS",
    ],
    langauge_Backend: [],
  },
  {
    colour: "bg-[#EEEEEE]",
    title: "FoodOrder & AdminDashboard",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/food.png",
    iconBg: "#E6DEDD",
    PROJECT_SHORT_NAME: "FullStackFoodOrder&AdminDashboard",
    PROJECT_NAME: "FullStackFood Order & AdminDashboard (Responsive Web App)",
    PROJECT_IMG: "/pj2.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "/mui.png",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "/graphql.png",
    nodejs: "/nodejs.png",
    Express: "Express",
    mongodb: "",
    Firebase: "/Firebase.png",
    mysql: "/stripe.webp",
    postger: "/webhook.svg",
    prisma: "",
    Nextjs: "/next.png",
    Ts: "/ts.png",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/AdminDashboard.git",
    Backend_Repo_Link: "https://github.com/HyatMyat4/DeshboardBackend.git",
    PROJECT_VIDEO: "yF1oJ7wzvWY",
    LIVE_MODE: "https://admin-dashboard-hyatmyat4.vercel.app/",
    PROJECT_TEXT:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin only can delete User and Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Git hub , instgram , Face Book , FastFood Auth     ",

    USER_LANGUAGE_IMG: [
      "/ts.png",
      "/tailwind.png",
      "/mui.png",
      "/react.png",
      "/redux.png",
      "/icons.svg",
      "/nodejs.png",
      "Express",
      "/Firebase.png",
      "/stripe.webp",
      "/webhook.svg",
      "/next.png",
      "/graphql.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "TailwindCss",
      "Material-ui",
      "React-icons",
      "Type Script",
    ],
    langauge_Backend: [
      "Node js",
      "Express Js",
      "Jwt Auth",
      "FireBase Db",
      "Graphql",
      "Next JS",
      "Stripe",
    ],
  },
  {
    colour: "bg-[#23242A]",
    title: "FullStackSocalMedia",
    company_name: "Full Stack (Responsive Web App)",
    icon: "/grape.png",
    iconBg: "#383E56",
    PROJECT_SHORT_NAME: "FullStackSocalMedia",
    PROJECT_NAME: "Full Stack SocalMedia (Responsive Web App)",
    PROJECT_IMG: "/project2.png",
    js: "/js.png",
    tailwind: "/tailwind.png",
    mui: "/mui.png",
    react: "/react.png",
    redux: "/redux.png",
    icons: "/icons.svg",
    pusher: "/pusher.png",
    nodejs: "/nodejs.png",
    Express: "Express",
    mongodb: "/mongodb.png",
    Firebase: "",
    mysql: "",
    postger: "",
    prisma: "",
    Nextjs: "",
    Ts: "",
    Frontend_Repo_Link: "https://github.com/HyatMyat4/GrapeMedia.git",
    Backend_Repo_Link: "https://github.com/HyatMyat4/SocialMediaBackend-.git",
    PROJECT_VIDEO: "cLKsNVSyPMM",
    LIVE_MODE: "",
    PROJECT_TEXT:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text",
    USER_LANGUAGE_IMG: [
      "/js.png",
      "/tailwind.png",
      "/mui.png",
      "/react.png",
      "/redux.png",
      "/icons.svg",
      "/pusher.png",
      "/nodejs.png",
      "Express",
      "/mongodb.png",
    ],
    langauge_Frontend: [
      "Java Script",
      "React",
      "Redux",
      "TailwindCss",
      "Material-ui",
      "React-icons",
    ],
    langauge_Backend: ["Node js", "Express Js", "Jwt Auth", "Mongo Db"],
  },
];

export { services, experiences, Projectdata, OrderBy };
